version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: daily
    reviewers:
      - Smaug6739
    assignees:
      - Smaug6739
