name: deploy to dev
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to dev
        run: |
          eval "$(ssh-agent -s)"
          cd /home/smaug/Spiritus/dev
          git stash
          git pull origin dev
          yarn install --production --frozen-lockfile
          yarn build
          pm2 reload beta.ecosystem.config.js
