#name: deploy to dev
# on:
#  push:
#    branches: [dev]
#jobs:
#  build:
#    runs-on: self-hosted
#    steps:
#      - name: Deploy to dev
#        run: |
#          cd /home/smaug/Spiritus/dev
#          git remote -v
#          git pull origin dev
